title: Your awesome title
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "twitter_username:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

url: ""
baseurl: ""

twitter_username: jekyllrb
github_username:  jekyll
rss: rss

show_excerpts: false
postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock

#theme: jekyll-theme-foursquare-church

plugins:
  - jekyll-postcss
  - jekyll-feed
  - jekyll-seo-tag