title: Your awesome title
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "twitter_username:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

url: ""
baseurl: "/jekyll-theme-foursquare-church"

twitter_username: jekyllrb
github_username:  jekyll
rss: rss

background: burlap # burlap, chalkboard, linen, wood
map:
  title: Visit Our Church
  map_img: https://maps.googleapis.com/maps/api/staticmap?center=Brooklyn+Bridge,New+York,NY&zoom=13&size=570x240&maptype=roadmap&markers=color:blue%7Clabel:S%7C40.702147,-74.015794&markers=color:green%7Clabel:G%7C40.711614,-74.012318&markers=color:red%7Clabel:C%7C40.718217,-73.998284&key=YOUR_API_KEY&signature=YOUR_SIGNATURE

service_times:
  - sunday: 9:00 a.m. - 2:00 p.m.
  - monday: 9:00 a.m. - 2:00 p.m.
  - tuesday: 9:00 a.m. - 2:00 p.m.
  - wednesday: 9:00 a.m. - 2:00 p.m.
  - thursday: 9:00 a.m. - 2:00 p.m.
  - friday: 9:00 a.m. - 2:00 p.m.
  - saturday: 9:00 a.m. - 2:00 p.m.

sliders:
  width: 1170
  height: 250
  animation: fade # fade, slide, show
  speed: 8.0 # 0.5 to 10.0 in seconds
  delay: 0.5 # 0.5 to 10.0 in seconds
  autoplay: true

show_excerpts: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
  - jekyll-theme-foursquare-church.gemspec

#theme: jekyll-theme-foursquare-church

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-asciidoc

asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    icons: font
    idseparator: _
    stylesdir: css
    source-highlighter: coderay